### PR TITLE
Feature: Http and Prometheus Updater

### PR DESCRIPTION
**Pull request by n14s**
Address #34 

This PR contains two new updater components, their example modules and an auxiliary component:
- Http Polling Updater
- Prometheus Updater
- Http-jsonata-aas example
- Prometheus-jsonata-aas example
- Timer (auxiliary component)

With these components, data from Http or Prometheus Endpoints can be integrated into the AAS.
Especially integrating device data via tools like Prometheus is essential for creating digital twins via AAS.

Technical details:
- Prometheus component is an extension of the Http component facilitating the query of metrics
- Route creation in Route Builder has been extended to support the components
- Http example works out of the box, Prometheus example requires a basic Prometheus + nodeexporter instance running

Open issue - Camels Http component doesn't fit well into Basyx Updater route scheme:
- Routes and route creation works different with camels http component, as it starts with a timer 
  from(timer).to(consumer).to(producer)
  instead of the datasource 
  from(consumer).to(producer)
- Therefore, conforming the Updater route scheme provides: 
  Datasource = timer 
  Datasink[0] = Http/Prometheus 
  Datasink[1] = AAS
- This can be explored in the routes.json of the Http/Prometheus examples
- In this PR the workaround results in a working solution, but the Basyx Updater scheme should be altered for a cleaner integration of http endpoints

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Many thanks for providing this PR! 
Currently, I see some merge conflicts. Can you take a look at resolving them? Let me know if you need any support.

Additionally, you need to use the same mail address in the commits like you used in the Eclipse Contributor Agreement. Would it be possible to update your commits in this regard?

**Comment by FrankSchnicke** [comment]
Many thanks for updating your PR. However, the merge conflicts & the issue with Eclipse Contributor Agreement still persist. Would it be possible to update your PR to address these two issues?

**Comment by n14s** [comment]
Hey Frank,
I'm currently still working on this PR. I'll finish it up when I'm done with other tasks, some of them also concerning this project.

Unluckily PR #37 added a updater component called "camel-http", just like my http-component. 
They serve different purposes though. 
While my http-component is used to poll data into the aas, PR #37 is used as a helper-component for the delegator iiuic.
I say "helper-component", because due to the reasons stated in the original PR message, it won't be able to work to serve as datasource.

I'm thinking of renaming it my http-component to maybe camel-http-polling and create a new PR or reopen this one.
When the open issue in the original PR message is solved they might be joined/ one might be omitted.

**Comment by FrankSchnicke** [comment]
Hi nik,

many thanks for providing these details. Renaming your component would be perfectly fine with me. If you need any support just let me know.

Best regards,
Frank

**Pull request closed without merging**
